openapi: 3.0.0
info:
  title: myFixer API
  description: Docs made for myFixer app️️️️
  version: 0.0.1
  host: localhost:3000
tags:
  - name: Accounts
paths:
  /accounts/sign-in:
    $ref: methods/accounts/signIn.yml
servers:
  - url: /api
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
# security:
#   - ApiKeyAuth: []
